let arr = [1, 2, 3];
console.log (arr);
let arr1 = ['пн', 'вт', 'ср', 'чт', 'пт', 'сб', 'вс'];
console.log (arr1[0]);
console.log (arr1[1]);
console.log (arr1[2]);
console.log (arr1);

let arr2 = ['a', 'b', 'c', 'd'];
console.log(arr2[0] + arr2[1] + arr2[2] + arr2[3]);
let arr3 = [1, 2, 3];
console.log(arr3[0] + arr3[1] + arr3[2]);

let arr4 = [2, 5, 3, 9];
result = arr4[0] * arr4[1] + arr4[2] * arr4[3];
console.log(result);
console.log(arr4.length);
console.log(arr3.length + arr2.length);

let arr5 = [1, 2, 3];
arr5[1] = '!';
console.log(arr5);
arr5[0] = '?';
arr5[2] = '~';
console.log(arr5);
arr5[0] = arr5[0] + '!';
arr5[1] = arr5[1] + '!';
arr5[2] = arr5[2] + '!';
console.log(arr5);
arr5[0] += '!';
arr5[1] += '!';
arr5[2] += '!';
console.log(arr5);
arr1[0] += '?';
arr1[1] += '?';
arr1[2] += '?';
arr1[3] += '?';
arr1[4] += '?';
arr1[5] += '?';
arr1[6] += '?';
console.log(arr1);
arr[0] += 3;
arr[1] += 3;
arr[2] += 3;
console.log (arr);
arr[0] ++;
--arr[1];
++arr[2];
console.log (arr);

let arr6 = [];
arr6[0] = 1;
arr6[1] = 2;
arr6[2] = 3;
console.log(arr6);
arr6[3] = '?';
arr6[4] = '!';
arr6[5] = 'мой массив';
console.log(arr6);
console.log(arr6[6]);
arr6[7] = 'word';
console.log(arr6);
console.log(arr[6]);
console.log(arr6.length);
